### PR TITLE
adding the license to the repo

### PR DESCRIPTION
**Pull request by sahnaseredini**
adding the license to the repo

### CODE REVIEW

**Comment by alexmurray** [comment]
Since this is just a library I thought it should instead be licensed under the GPL - not the AGPL?

**Comment by sahnaseredini** [comment]
Thanks for the review Alex.

I was thinking about it more as a code that's running in the background on the server side, that's why I chose AGPL. I 'll quickly change it to GPL then. Thanks

**Comment by alexmurray** [comment]
AGPL is used when the thing is deployed as a backend - since in this case this is really just a tool which can be deployed in a variety of ways, I think the GPL3 makes more sense.

**Review by alexmurray — APPROVED** [review]
LGTM!

**Pull request merged**
